proyecto_final/miscosas/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index),
    path('logged', views.index),
    path('informacion', views.giveInf),
    path('user/<slug:usuario>', views.userProfile),
    path('user/<str:usuario>/darkmode', views.darkMode),
    path('user/<str:usuario>/letra', views.leterDim),
    path('user_list', views.userList),
    path('alim_list', views.alimList),
    path('alimentador', views.alimentador),
    path('alim_red', views.redirectAlim),
    path('alim/<str:item_id>', views.seeItem),
    path('alim/<str:item_id>/votar', views.votar),
    path('alim/<str:item_id>/comentar', views.addComment),
    path('register', views.register),
    path('login', views.login),
    path('logout', views.logout),
    path('delete', views.delete),
    path('i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_final/proyecto_final/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView as login
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('miscosas/', include('miscosas.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_final/miscosas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Alimentador(models.Model):
    id = models.CharField(max_length=64, primary_key=True)
    title = models.CharField(max_length=64, null=True)
    link = models.CharField(max_length=64, null=True)
    canal_items = models.IntegerField(default=0, null = True)
    puntuacion = models.IntegerField(default=0)
    selected = models.BooleanField(default = True)
    type = models.CharField(max_length=64, null=True)

    def __str__(self):
        return self.title

class Item(models.Model):
    alim = models.ForeignKey(Alimentador, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=64, null=True)
    link = models.CharField(max_length=64, null=True)
    id = models.CharField(max_length=64, primary_key=True)
    description = models.CharField(max_length=256, null=True)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    fecha = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Item_voted(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    voto = models.IntegerField(default=0)

    def __str__(self):
        return "El usuario " + self.usuario.username + " ha votado: " + self.item.title

class Comentario(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    concepto = models.CharField(max_length=64, null=True)
    coment = models.TextField(max_length=256, null=True)
    fecha = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "El usuario " + self.usuario.username + " ha comentado: " + self.item.title

class Perfil(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='images/', default = "images/defecto.jpg")
    darkmode = models.BooleanField(default = False)
    dimension = (('p', 'Pequeña'),('m', 'Mediana'),('g', 'Grande'),)
    dim_let = models.CharField(max_length=1, choices=dimension, blank=True, default='m', help_text='Que tamaño quieres para tu letra')
    visits = models.IntegerField(default=0)

    def __str__(self):
        return self.usuario.username

proyecto_final/miscosas/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Perfil

class takeImage(forms.ModelForm):

    class Meta:
        model = Perfil
        fields = ('foto',)

proyecto_final/miscosas/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout
from .models import Alimentador, Item, Item_voted, Comentario, Perfil
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .youtube_parser import YTChannel
from .last_parser import LastArtist
from .wiki_parser import WikiArticle
from .key import LASTFM_APIKEY
from django.contrib.auth.models import User
from .forms import takeImage
import operator
import urllib
import json
from django.conf import settings
from django.utils import translation

def register(request):
    formreg = UserCreationForm()
    form = AuthenticationForm()
    Alimentadores = Alimentador.objects.all()
    top10 = top10items()

    if request.method == "POST":
        formreg = UserCreationForm(data=request.POST)
        if formreg.is_valid():
            usuario = formreg.save()
            perfil = Perfil(usuario= usuario)
            perfil.save()
            if usuario is not None:
                do_login(request, usuario)
                return redirect('/miscosas/logged')

    formularios = {'formreg': formreg, 'form': form}
    content = {'Alimentadores': Alimentadores, 'top10': top10}
    diccionarios = {**content, **formularios}

    return render(request, "miscosas/register.html", diccionarios)

def index(request):
    Alimentadores = Alimentador.objects.all()
    user = request.user
    try:
        last5 = list(Item_voted.objects.filter(usuario=user))[-5:]
    except:
        last5 =""
    try:
        perfil = Perfil.objects.get(usuario = user)
    except:
        perfil = Perfil.objects.none()
    try:
        foto = Perfil.objects.get(usuario = user).foto
    except:
        foto = '/images/defecto.jpg'
    top10 = top10items()
    content = {'Alimentadores': Alimentadores, 'foto': foto, 'top10': top10, 'perfil': perfil, 'last5': last5}

    if request.method == 'GET':
        form = request.GET.get('form')
        if form != '':
            if form == "json":
                alimList =[]
                for alim in Alimentadores:
                    alimList.append(str(alim))
                topList =[]
                for top in top10:
                    topList.append(str(top))
                lastList =[]
                for last in last5:
                    lastList.append(str(last))
                content = {'Alimentadores': alimList, 'top10': topList, 'last5': lastList}
                contents = json.dumps(content)
                return HttpResponse(contents, content_type="application/json")

            elif form == "xml":
                return render(request, 'miscosas/principal.xml', content, content_type='application/xml')

    if request.user.is_authenticated:
        return render(request, "miscosas/index.html", content )

    return redirect('/miscosas/login')

def login(request):
    form = AuthenticationForm()
    Alimentadores = Alimentador.objects.all()
    top10 = top10items()
    try:
        last5 = list(Item_voted.objects.filter(usuario=request.user))[-5:]
    except:
        last5 =""
    try:
        perfil = Perfil.objects.get(usuario = request.user)

    except:
        perfil = Perfil.objects.none()
    try:
        foto = Perfil.objects.get(usuario = request.user).foto
    except:
        foto = '/images/defecto.jpg'
    content = {'Alimentadores': Alimentadores, 'foto': foto,'top10': top10, 'perfil': perfil, 'last5': last5}

    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                try:
                    perfil = Perfil.objects.get(usuario = user)
                    perfil.visits = perfil.visits + 1
                    perfil.save()
                except:
                    perfil = Perfil.objects.none()
                do_login(request, user)
                return redirect('/miscosas/logged')

    diccionarios ={**content, **{'form': form}}
    return render(request, "miscosas/index.html",diccionarios)


def logout(request):
    do_logout(request)
    return redirect('/miscosas')

def top10items ():
    best = {}
    lista_items = []
    items = Item.objects.all()

    for element  in items:
        votos = Item_voted.objects.filter(item = element)
        likes = votos.filter(voto = 1).count()
        dislikes = votos.filter(voto = -1).count()
        total = likes - dislikes
        best[element.link] = total
    orden = sorted(best.items(), key=operator.itemgetter(1), reverse = True)
    orden = orden[0:10]
    for id, votos in orden:
        try:
            item = Item.objects.get(link=id)
        except Item.DoesNotExist:
            return HttpResponse("Insertar error")
        lista_items.append(item)
    return lista_items

def parse(request, id, action):
    if action == 'YouTube':
        if id != '':
            xml = "https://www.youtube.com/feeds/videos.xml?channel_id=" + id
            xmlStream = urllib.request.urlopen(xml)
            channel = YTChannel(xmlStream)
    elif action == 'Last':
        if id != '':
            xml = "http://ws.audioscrobbler.com/2.0/?method=artist.gettopalbums&artist=" + id + "&api_key=" + LASTFM_APIKEY
            xmlStream = urllib.request.urlopen(xml)
            channel = LastArtist(xmlStream)
    elif action == 'Wikipedia':
        if id != '':
            nombre = id.split()[0]
            xml = "https://en.wikipedia.org/w/index.php?title=" + nombre + "&action=history&feed=rss"
            xmlStream = urllib.request.urlopen(xml)
            channel = WikiArticle(xmlStream)

def alimentador(request):
    form = AuthenticationForm()
    Alimentadores = Alimentador.objects.all()
    top10 = top10items()
    try:
        last5 = list(Item_voted.objects.filter(usuario=request.user))[-5:]
    except:
        last5 =""
    try:
        perfil = Perfil.objects.get(usuario = request.user)
    except:
        perfil = Perfil.objects.none()
    try:
        foto = Perfil.objects.get(usuario=request.user).foto
    except:
        foto = '/images/defecto.jpg'

    if request.method == 'POST':
        action = request.POST['Alimentador']
        id = request.POST['id']
        try:
            if action == 'YouTube':
                alim = Alimentador.objects.get(id=id)
            if action == 'Wikipedia':
                alim = Alimentador.objects.get(title=id)
            elif action =="actualizar":
                alim = Alimentador.objects.get(id=id)
                action = alim.type
                if alim.type == "Last":
                    id = alim.title
                parse(request, id, action)
                if action == 'YouTube':
                    alim = Alimentador.objects.get(id=id)
                else:
                    alim = Alimentador.objects.get(title=id)
            else:
                alim = Alimentador.objects.get(title=id)


        except:
            parse(request, id, action)
            if action == 'YouTube':
                alim = Alimentador.objects.get(id=id)
            else:
                alim = Alimentador.objects.get(title=id)
        alim.selected = True
        alim.save()
    Items = Item.objects.filter(alim=alim)
    Items_ord = sorted(Items, key=lambda x: x.fecha)
    if action == 'YouTube':
        destiny = 'miscosas/alimentador.html'
        content = {'channel': alim, 'Videos': Items_ord,
                    'usuario': request.user, 'Alimentadores': Alimentadores, 'foto': foto, 'top10':top10, 'perfil': perfil, 'last5': last5}
    elif action == 'Wikipedia':
        destiny = 'miscosas/wikipedia.html'
        content = {'article': alim, 'Changes': Items_ord,
                    'usuario': request.user, 'Alimentadores': Alimentadores, 'foto': foto, 'top10':top10, 'perfil': perfil, 'last5': last5}
    else:
        destiny = 'miscosas/last.html'
        content = {'artist': alim, 'Albumes': Items_ord,
                    'usuario': request.user, 'Alimentadores': Alimentadores, 'foto': foto, 'top10':top10, 'perfil': perfil, 'last5': last5}

    diccionarios ={**content, **{'form': form}}
    return render(request, destiny, diccionarios)

def redirectAlim(request):
    form = AuthenticationForm()
    Alimentadores = Alimentador.objects.all()
    top10 = top10items()
    try:
        last5 = list(Item_voted.objects.filter(usuario=request.user))[-5:]
    except:
        last5 =""
    try:
        perfil = Perfil.objects.get(usuario = request.user)
    except:
        perfil = Perfil.objects.none()
    try:
        foto = Perfil.objects.get(usuario= request.user).foto
    except:
        foto = '/images/defecto.jpg'

    if request.method == 'POST':
        id = request.POST['id']
        alim = Alimentador.objects.get(id=id)
    if alim.type == 'YouTube':
        destiny = 'miscosas/alimentador.html'
        content = {'channel': alim, 'Videos': Item.objects.filter(alim=alim),
                    'usuario': request.user, 'Alimentadores': Alimentadores, 'foto': foto, 'top10':top10, 'perfil': perfil, 'last5': last5}
    elif alim.type == 'Wikipedia':
        destiny = 'miscosas/wikipedia.html'
        content = {'article': alim, 'Changes': Item.objects.filter(alim=alim),
                    'usuario': request.user, 'Alimentadores': Alimentadores, 'foto': foto, 'top10':top10, 'perfil': perfil, 'last5': last5}
    else:
        destiny = 'miscosas/last.html'
        content = {'artist': alim, 'Albumes': Item.objects.filter(alim=alim),

proyecto_final/miscosas/templates/miscosas/alim_list.html
{% extends 'miscosas/index.html' %}
{% load i18n %}
{% block contenidos %}


  <div id = "alimentadores">
  <h2>{% trans 'Alimentadores' %}</h2>
    {% for alim in Alimentadores %}
      {% if alim.selected %}
        <li>{% trans 'El nombre del alimentador es:' %} {{ alim }}
          <br>{% trans 'Link al Alimentador:' %} <a href='{{alim.link}}'>{{ alim }}</a>
          <br>{% trans 'Tiene un total de' %} {{alim.canal_items}} items.
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

proyecto_final/miscosas/templates/miscosas/alimentador.html
{% extends 'miscosas/index.html' %}
{% block contenidos %}
{% load i18n %}

    <h2> {% trans 'Lista de Items:' %} {{channel.title}}</h2>
  <p> <a href="{{ channel.link }}"> {% trans 'ver Alimentador' %} </a></p>
  <form method="POST" action="/miscosas/alimentador">
    {% csrf_token %}
    <input type="hidden" name="id" value = {{channel.id}}>
    <input type="submit" name="Alimentador" value="actualizar">
  </form>
  <form method="POST" action="/miscosas/delete">
    {% csrf_token %}
    <input type="hidden" name="id" value = "{{channel.id}}">
    <input type="submit" name="Alimentador" value="Borrar">
  </form>
  {% for video in Videos %}
  <li>{% trans 'Titulo:' %}
    <a href='{{video.link}}'> {{video.title}}</a>
  </li>
  <li>
    <p> {% trans 'ver el item en esta pagina' %}  <a href="/miscosas/alim/{{ video.id }}"> {% trans 'aqui' %} </a>
  </li>
  {% endfor %}
{% endblock %}

proyecto_final/miscosas/templates/miscosas/index.html
<!DOCTYPE html>
  {% load static %}
  {% load i18n %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link  rel="icon"  type="image/png" href="{% static "miscosas/urjc.png" %}"  />
    <link rel="stylesheet" type="text/css" href="{% static "miscosas/main.css" %}">
    {% if perfil.darkmode and user.is_authenticated %}
      <link rel="stylesheet" type="text/css" href="{% static "miscosas/oscuro.css" %}">
    {% endif %}
    {% if perfil.dim_let == 'p' %}
      <link rel="stylesheet" type="text/css" href="{% static "miscosas/pequenia.css" %}">
    {% elif perfil.dim_let == 'g' %}
      <link rel="stylesheet" type="text/css" href="{% static "miscosas/grande.css" %}">
    {% endif %}
    <title> Esta es la pagina de mis cosas</title>
    <title>{% trans "Esta es la pagina de mis cosas" %}</title>
  </head>

  <body>

    <div id = cabecera>
      <div id=imagen>
        <img src="{% static "miscosas/miscosas.jpeg" %}" alt="My image"  width: "50" height: "50">
        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
  		    <input name="next" type="hidden" value="{{ redirect_to }}">
  		    <select name="language">
  		        {% get_current_language as LANGUAGE_CODE %}
  		        {% get_available_languages as LANGUAGES %}
  		        {% get_language_info_list for LANGUAGES as languages %}
  		        {% for language in languages %}
  		            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
  		                {{ language.name_local }} ({{ language.code }})
  		            </option>
  		        {% endfor %}
  				 </select>
  				 <input type="submit" value="{% trans "ir" %}">
  				</form>
      </div>
      <div id= titulo> <h1> {% trans 'Mis Cosas' %} </h1> </div>
      <div id = login>
        {% if not user.is_authenticated %}
          <h2> {% trans "Iniciar sesion" %} </h2>
          <form method="POST" action = "/miscosas/login">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit">Login</button>
          </form>
          <p><a href= "register">{% trans "¿No tienes cuenta?" %}</a></p>
        {% else %}
        <div id = logged>
          <img src= {{foto}} alt = "Imagen de perfil" style= width:60px;height:60px;>
          <p> {% trans "Bienvenido" %} {{ user.username }}</p>
          <p> {% trans 'Has entrado' %} {{perfil.visits}} {% if perfil.visits == 1 %} {% trans 'vez.' %} {% else %} {% trans 'veces.'%}{% endif %}
          <p><a href= "/miscosas/logout">logout</a></p>
        </div>
        {% endif %}
      </div>
    </div>
  <div id = "cuerpo">
    <div id="ventanas">
      <nav><ul>
        {% if request.path != "/miscosas/login" and request.path != "/miscosas/logged" and request.path != "/miscosas/"%}
      <li><a href="/miscosas/">{% trans 'Inicio' %}</a></li>
        {% endif %}
      {%  if user.is_authenticated %}
        {% if request.path != "/miscosas/user/{{user.username}}" %}
          <li><a href="/miscosas/user/{{user.username}}">{% trans 'Mi perfil' %}</a></li>
        {% endif %}
      {% endif %}
      {% if request.path != "/miscosas/alim_list" %}
        <li ><a href="/miscosas/alim_list">{% trans 'Alimentadores' %}</a></li>
      {% endif %}
      {% if request.path != "/miscosas/user_list" %}
        <li><a href="/miscosas/user_list">{% trans 'Usuarios' %}</a></li>
      {% endif %}
      {% if request.path != "/miscosas/informacion" %}
        <li><a href="/miscosas/informacion">{% trans 'Información' %}</a></li>
      {% endif %}
    </ul></nav>
    </div>

    <div id="buscadores">
      <form method="POST" action="/miscosas/alimentador">
        {% csrf_token %}
        <br>{% trans 'Videos de un Canal de Youtube:' %} <input type="text" name="id">
        <input id="boton" type="submit" name="Alimentador" value="YouTube">
      </form>

      <form method="POST" action="/miscosas/alimentador">
        {% csrf_token %}
        <br>{% trans 'Albumes de un artista:' %} <input type="text" name="id">
        <input id="boton" type="submit" name="Alimentador" value="Last">
      </form>

      <form method="POST" action="/miscosas/alimentador">
        {% csrf_token %}
        <br>{% trans 'Articulo de Wikipedia:' %} <input type="text" name="id">
        <input id="boton" type="submit" name="Alimentador" value="Wikipedia">
      </form>
    </div>
    <hr>
    <div id = interaccion>
      <div id = "alimentadores">
      <h2>{% trans 'Alimentadores' %}</h2>
          {% for alim in Alimentadores %}
          {% if alim.selected %}
            <li>{% trans 'El nombre del canal es:' %} {{ alim }}
              <br>{% trans 'Link al canal:' %} <a href='{{alim.link}}'>{{ alim }}</a>
              <br>{% trans 'Tiene un total de ' %} {{alim.canal_items}} items.
              <br>{% trans 'Su valance de puntuacion es:' %} {{alim.puntuacion}}

                <form method="POST" action="/miscosas/alim_red">
                  {% csrf_token %}
                  <input type="hidden" name="id" value = "{{alim.id}}">
                  <input type="submit" name="Alimentador" value="ir">
                </form>
                 <form method="POST" action="/miscosas/delete">
                   {% csrf_token %}
                   <input type="hidden" name="id" value = "{{alim.id}}">
                   <input type="submit" name="Alimentador" value="Borrar">
                 </form>
             </li>
          {% endif %}
          {% endfor %}
      </div>
      <div id = "videos">
        {% block contenidos %}
        {% endblock %}

      </div>
      <div id = "tops">
        <ul>
          <li><h2> {% trans '10 items mas votados' %} </h2>
          <ul>
          {% for top in top10 %}
            <li>
              <p>{{top.title}}</p>
              <p>pos: {{top.likes}} neg:{{top.dislikes}}
              <p> <a href='/miscosas/alim/{{top.id}}'> Ver item</a>
            </li>
          {% endfor%}
          </ul></li>
        </ul>
          {%  if user.is_authenticated %}
          <ul>
            <li><h2> {% trans '5 ultimos items votados' %} </h2>
            <ul>
            {% for last in last5 %}
              <li>
                <p>{{last.item.title}}</p>
                {% if last.voto == 1 %}
                  <td><input type="submit" name="voto" value="like" id = "like"></td>
                  <td><input type="submit" name="voto" value="dislike" disabled = True></td>
                {% else %}
                  <td><input type="submit" name="voto" value="like" disabled =  True></td>
                  <td ><input type="submit" name="voto" value="dislike" id ="dislike"></td>
                {% endif %}
                <p> <a href='/miscosas/alim/{{last.item.id}}'> Ver item</a>
            {% endfor%}
            </ul>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
  <footer id = pie>
    <p>{% trans 'Esta página ha sido realizada con datos de' %} <a href="https://www.youtube.com/?hl=es&gl=ES">YouTube</a>, de
      <a href="https://www.last.fm/es/home">Last.fm </a> {% trans 'y de' %} <a href="https://en.wikipedia.org/wiki/Main_Page">Wikipedia </a></p>
    <p> {% trans 'Hecho por:' %} <a href="https://gitlab.etsit.urjc.es/jffuncia/final-miscosas"> jffuncia</a></p>
      <form method="GET" action="/miscosas/">
        {% csrf_token %}
        {% trans 'Obtener la pagina principal en XML' %} <input type="submit" name="form" value = "xml">
      </form>
      <form method="GET" action="/miscosas/">
        {% csrf_token %}
        <br> {% trans 'Obtener la pagina principal en JSON' %} <input type="submit" name="form" value = "json">
      </form>
  </footer>
  </body>
</html>

proyecto_final/miscosas/templates/miscosas/informacion.html
{% extends 'miscosas/index.html' %}
{% block contenidos %}
{% load i18n %}

  <h2> {% trans 'Informacion del sitio' %}</h2>
    <p> Pagina web sobre mis cosas hecha por Jesús Fernández Funcia, alumno del grado de tecnologías de la Telecomunicación.</p>
    <p> En esta página podrás ver canales y videos de Youtube, artistas de música y sus albumes y articulos de wikipedia con sus
      modificaciones. Ademas, podras registrarte para poder votarlos y comentarlos.</p>
    <p> Para ver un canal de Youtube, tienes que introducir el id de un canal de youtube en el alimetador de Youtube; si quieres ver
      un artista, introduce el nombre del artista en el alimetador Last; y para ver las modificaciones de un articulo de Wikipedia,
      inserta el nombre del articulo en el alimentador Wikipedia. </p>
    <p> Una vez te hayas registrado, vas a poder cambiar cambiar tu foto de perfil y ver cuales han sido tus ultimos items votados,
      y para tu comodidad, puedes poner el  modo oscuro o cambiar el tamaño de la letra. Tambien podrás ver el perfil de tus amigos
      y ver que han comentado y votado.</p>
    <p> Si quieres ir un poco mas lejos, tienes abajo el Gitlub de esta pagina web y un enlace para ver la página principal en formato
      JSON o XML.</p>
{% endblock %}

proyecto_final/miscosas/templates/miscosas/last.html
{% extends 'miscosas/index.html' %}
{% block contenidos %}
{% load i18n %}

  <h2> {% trans 'Artista buscado:' %} {{artist.title}}</h2>
  <p><a href="{{ artist.link }}"> {% trans 'ver artista' %} </a></p>
  <form method="POST" action="/miscosas/alimentador">
    {% csrf_token %}
    <input type="hidden" name="id" value = {{artist.id}}>
    <input type="submit" name="Alimentador" value="actualizar">
  </form>
  <form method="POST" action="/miscosas/delete">
    {% csrf_token %}
    <input type="hidden" name="id" value = "{{artist.id}}">
    <input type="submit" name="Alimentador" value="Borrar">
  </form>
  {% for album in Albumes %}
  <li>Album:
    <a href='{{album.link}}'> {{album.title}}</a>
  </li>
  <li>
    <p> {% trans 'ver el album en esta pagina' %}  <a href="/miscosas/alim/{{album.id}}"> {% trans 'aqui' %} </a>
  </li>
  {% endfor %}
{% endblock %}

proyecto_final/miscosas/templates/miscosas/register.html
{% extends 'miscosas/index.html' %}
{% block contenidos %}
{% load i18n %}

<h2>{% trans 'Registrar nuevo usuario' %}</h2>

<form method="POST">
    {{ formreg.as_p }}
    {% csrf_token %}
    <button type="submit">{% trans 'Registrar' %}</button>
</form>

{% endblock %}

proyecto_final/miscosas/templates/miscosas/usuarios_list.html
{% extends 'miscosas/index.html' %}
{% block contenidos %}
{% load i18n %}

  <h2> {% trans 'Lista de usuarios' %}</h2>
  {%for user in usuarios %}
    <li> <img src= '{{user.foto.url}}' style= width:50px;height:40px;>
      <br> {{user.usuario}}
      <br> {% trans 'Ha votado' %} {{user.usuario.item_voted_set.count}} items
      {% trans 'y ha comentado otros' %} {{user.usuario.comentario_set.count}}.
      <br><a href='user/{{user.usuario}}'> {% trans 'Ver perfil' %} </a>
    </li>
  {%endfor%}
{%endblock%}

proyecto_final/miscosas/templates/miscosas/wikipedia.html
{% extends 'miscosas/index.html' %}
{% block contenidos %}
{% load i18n %}

    <h2> {% trans 'Articulo buscado:' %} {{article.title}}</h2>
  <p> <a href="{{ article.link }}"> ver modificaciones </a></p>
  {{article.id}}
  <form method="POST" action="/miscosas/alimentador">
    {% csrf_token %}
    <input type="hidden" name="id" value = {{article.id}}>
    <input type="submit" name="Alimentador" value="actualizar">
  </form>
  <form method="POST" action="/miscosas/delete">
    {% csrf_token %}
    <input type="hidden" name="id" value = "{{article.id}}">
    <input type="submit" name="Alimentador" value="Borrar">
  </form>
  {% for change in Changes %}
  <li>{% trans 'Titulo:' %}
    <a href='{{change.link}}'> {{change.title}}</a>
  </li>
  <li>
    <p> {% trans 'ver la modificación del artículo' %}  <a href="/miscosas/alim/{{ change.id }}"> {% trans 'aqui' %} </a>
  </li>
  {% endfor %}
{% endblock %}